### ISSUE TITLE
Mini Cheat Sheet issue

### ISSUE THREAD

**Issue by I3Tank** [ieshreya/Obsidian-Cheat-Sheet#3]
Spacer is missing a third -
Is -- instead of ---

Thank you very much for this cheat sheet!

**Comment by MarkisJr** [comment]
Noticed same issue. Very useful though, greatly appreciated ❤️

**Comment by ieshreya** [comment]
ah I just noticed, corrected it. Thank you!

By the way, I'm planning to work on this cheatsheet to make it even easier to understand in the next few days. Stay tuned for the updates! 😊
